
###

GET http://localhost:8529/_db/cupboard/faux_app/results?project=IQ&from=2019-03-15&to=2019-03-17/user/passwd HTTP/1.1
Authorization: Basic autotest ^HCBc#mdCSgGh2}


###

GET http://localhost:8529/_db/cupboard/faux_app/results/send?project=IQ&from=2019-03-15&to=2019-03-18/user/passwd HTTP/1.1
Authorization: Basic autotest ^HCBc#mdCSgGh2}


###

GET http://localhost:8529/_db/cupboard/faux_app/results/trend HTTP/1.1
Authorization: Basic autotest ^HCBc#mdCSgGh2}